# -*- coding: utf-8 -*-
"""
This family file was auto-generated by $Id$
Configuration parameters:
  url = http://lyrics.answers.wikia.com/wiki/Music_and_Lyrics_Answers
  name = musicanswers

Please do not commit this to the Git repository!
"""

import family

class Family(family.Family):
    def __init__(self):
        family.Family.__init__(self)
        self.name = 'musicanswers'
        self.langs = {
            'en': 'lyrics.answers.wikia.com',
        }

        self.namespaces[4] = self.namespaces.get(4, {})
        self.namespaces[4][u'en'] = [u'Music and Lyrics Answers']
        self.namespaces[5] = self.namespaces.get(5, {})
        self.namespaces[5][u'en'] = [u'Music and Lyrics Answers talk']
        self.namespaces[6] = self.namespaces.get(6, {})
        self.namespaces[6][u'en'] = [u'Image']
        self.namespaces[7] = self.namespaces.get(7, {})
        self.namespaces[7][u'en'] = [u'Image talk']
        self.namespaces[110] = self.namespaces.get(110, {})
        self.namespaces[110][u'en'] = [u'Forum']
        self.namespaces[111] = self.namespaces.get(111, {})
        self.namespaces[111][u'en'] = [u'Forum talk']
        self.namespaces[1200] = self.namespaces.get(1200, {})
        self.namespaces[1200][u'en'] = [u'Message Wall']
        self.namespaces[1201] = self.namespaces.get(1201, {})
        self.namespaces[1201][u'en'] = [u'Thread']
        self.namespaces[1202] = self.namespaces.get(1202, {})
        self.namespaces[1202][u'en'] = [u'Message Wall Greeting']
        self.namespaces[500] = self.namespaces.get(500, {})
        self.namespaces[500][u'en'] = [u'User blog']
        self.namespaces[501] = self.namespaces.get(501, {})
        self.namespaces[501][u'en'] = [u'User blog comment']
        self.namespaces[502] = self.namespaces.get(502, {})
        self.namespaces[502][u'en'] = [u'Blog']
        self.namespaces[503] = self.namespaces.get(503, {})
        self.namespaces[503][u'en'] = [u'Blog talk']
        self.namespaces[828] = self.namespaces.get(828, {})
        self.namespaces[828][u'en'] = [u'Module']
        self.namespaces[829] = self.namespaces.get(829, {})
        self.namespaces[829][u'en'] = [u'Module talk']


    def scriptpath(self, code):
        return {
            'en': '',
        }[code]

    def version(self, code):
        return {
            'en': u'1.19.20',
        }[code]
